Spring:
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2-data/SecurityOAuth
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
    locale: en
  profiles:
    include:
      - oauth
      - jwt
server:
  error:
    include-stacktrace: never
    include-binding-errors: never
logging.level:
  org.hibernate.type: trace
