Spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2-data/SecurityOAuth
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
    locale: en
server:
  error:
    include-stacktrace: never
    include-binding-errors: never
logging.level:
  org.hibernate.type: trace
